DROP TABLE IF EXISTS `rguru_pitchers`
CREATE TABLE `rguru_pitchers`(
    id VARCHAR(5),
    name VARCHAR(30),
    date DATE,
    dk_position VARCHAR(6),
    dk_pts DECIMAL(4,2),
    dk_salary INT,
    fd_position VARCHAR(6),
    fd_pts DECIMAL(4,2),
    fd_salary INT,
    team VARCHAR(3),
    opp VARCHAR(3),
    score VARCHAR(10),
    home_game CHAR(1),
    bat_order CHAR(1),
    start CHAR(1),
    IP DECIMAL (3,1),
    K INT,
    BB INT,
    R INT,
    ER INT,
    H INT,
    HB INT,
    E INT,
    Win INT,
    Loss INT,
    Save INT,
    Hold INT,
    CG INT
)


DROP TABLE IF EXISTS `rguru_hitters`
CREATE TABLE `rguru_hitters`(
    id VARCHAR(5),
    name VARCHAR(30),
    date DATE,
    dk_position VARCHAR(6),
    dk_pts DECIMAL(4,2),
    dk_salary INT,
    fd_position VARCHAR(6),
    fd_pts DECIMAL(4,2),
    fd_salary INT,
    team VARCHAR(3),
    opp VARCHAR(3),
    score VARCHAR(10),
    home_game CHAR(1),
    bat_order CHAR(1),
    start CHAR(1),
    H INT,
    AB INT,
    2B INT,
    3B INT,
    HR INT,
    BB INT,
    SO INT,
    RBI INT,
    SB INT,
    CS INT,
    S INT,
    SF INT,
    HBP INT,
    E INT
)